In [5]:
from __future__ import annotations

from typing import Union, Optional
import os

import numpy as np
import pandas as pd

from matplotlib import pyplot as plt
plt.style.use(os.path.join(os.path.expanduser('~'), 'default.mplstyle'))

In [6]:
players_2425_path = "./Quotazioni_Fantacalcio_Stagione_2024_25.csv"
players_2324_path = "./Quotazioni_Fantacalcio_Stagione_2023_24.csv"
stats_2425_path = "./Statistiche_Fantacalcio_Stagione_2024_25.csv"
stats_2324_path = "./Statistiche_Fantacalcio_Stagione_2023_24.csv"
# the latter is updated at the third round - 4rd Sep 2024

players_2425_df = pd.read_csv(players_2425_path, delimiter=",", header=1, index_col=False)
players_2324_df = pd.read_csv(players_2324_path, delimiter=",", header=1, index_col=False)
stats_2425_df = pd.read_csv(stats_2425_path, delimiter=",", header=1, index_col=False)
stats_2324_df = pd.read_csv(stats_2324_path, delimiter=",", header=1, index_col=False)

# basic functions

In [7]:
class Filter:

    def __init__(
            self: Filter, column: str, operation: str, value: Union[str, float]) -> None:
        self.column = column
        self.operation = operation
        self.value = value
    
    def apply_to_df(self: Filter, df: pd.DataFrame) -> pd.DataFrame:
        if self.operation == "ge":
            return df[df[self.column] > self.value]
        elif self.operation == "geq":
            return df[df[self.column] >= self.value]
        elif self.operation == "le":
            return df[df[self.column] < self.value]
        elif self.operation == "leq":
            return df[df[self.column] <= self.value]
        elif self.operation == "eq":
            return df[df[self.column] == self.value]
        elif self.operation == "neq":
            return df[df[self.column] != self.value]


def apply_multiple_filters(df: pd.DataFrame, filter_list: list[Filter]) -> pd.DataFrame:
    filtered_df = df.copy()
    for filter in filter_list:
        filtered_df = filter.apply_to_df(filtered_df)
    return filtered_df


def extract_players_mantra_position(df: pd.DataFrame, position: str) -> pd.DataFrame:
    """
    The mantra position is tricky, because they actually include multiple positions with ; as delimiter.
    The easiest way is to select the players where the mantra position column contains also that specific position.
    """
    return df[df["RM"].str.contains(position)]

In [13]:
def get_data_team_alba(team_alba: list[str]):
    data = {
        'draft_2324': players_2324_df[np.isin(players_2324_df["Nome"], team_alba)],
        'draft_2425': players_2425_df[np.isin(players_2425_df["Nome"], team_alba)],
        'stats_2324': stats_2324_df[np.isin(stats_2324_df["Nome"], team_alba)],
        'stats_2425': stats_2425_df[np.isin(stats_2425_df["Nome"], team_alba)],
    }

    # the first is not true anymore, as some players are not in Serie A anymore
    # assert len(data['draft_2425']) == 25
    assert len(data['stats_2425']) == 25
    return data

In [14]:
ac_st_leonards = ["Maignan", "Sportiello", "Torriani",
                  "Bijol", "Dimarco", "Dodo'", "Godfrey", "Lazzari", "Martinez Quarta", "N'Dicka", "Pavlovic",
                  "Dele-Bashiru", "Duda", "Ellertsson", "Forson O.", "Neres", "Orsolini", "Richardson", "Vlasic",
                  "Banda", "Krstovic", "Mbangula", "Okafor", "Sanchez", "Zapata D."]
    
tuttoculo = ["Joronen", "Milinkovic-Savic V.", "Vasquez D.",
             "Buongiorno", "Darmian", "Delprato", "Dumfries", "Gallo", "Tomori", "Viti", "Zanoli",
             "Baldanzi", "Barella", "Da Cunha", "Douglas Luiz", "Gyasi", "Lobotka", "Marchwinski", "Politano",
             "Abraham", "De Ketelaere", "Dovbyk", "Pavoletti", "Pinamonti", "Rocha Livramento"]

astolfone = ["Carnesecchi", "Mandas", "Pizzignacco",
             "Calabria", "De Winter", "Faraoni", "Hermoso", "Kalulu", "Marusic", "Mazzocchi", "Tavares N.",
             "Ekkelenkamp", "Ikone'", "Ilic", "McKennie", "McTominay", "Samardzic", "Viola", "Weah",
             "Djuric", "Gonzalez N.", "Martinez L.", "Noslin", "Pohjanpalo", "Vitinha O."]

tartan_viola = ["Di Gregorio", "Okoye", "Perin",
                "Acerbi", "Bellanova", "Di Lorenzo", "Idzes", "Kyriakopoulos", "Luperto", "Pezzella Giu.", "Zortea",
                "Bernabe'", "Colpani", "Fabbian", "Ferguson", "Harroui", "Locatelli", "Miretti", "Paz N.",
                "Belotti", "Benedyczak", "Caprari", "Mosquera", "Piccoli", "Retegui"]

schalke104 = ["Falcone", "Montipo'", "Turati",
              "Baschirotto", "Beukema", "Cabal", "Danilo", "Emerson Royal", "Hien", "Kossounou", "Zappacosta",
              "Conceicao", "Guendouzi", "Loftus-Cheek", "Messias", "Mkhitaryan", "Ndoye", "Saelemaekers", "Zambo Anguissa",
              "Castellanos", "Dybala", "Leao", "Milik", "Mota", "Yildiz"]

real_calloni = ["Caprile", "De Gea", "Meret",
                "Angelino", "Biraghi", "Carboni A.", "Carlos Augusto", "Gatti", "Sosa B.", "Spinazzola", "Valeri",
                "Fagioli", "Payero", "Pellegrini Lo.", "Reijnders", "Ricci S.", "Vignato S.", "Zaniolo", "Zielinski",
                "Brenner", "Dia", "Esposito Se.", "Lookman", "Luvumbo", "Morata"]

olympique_nicastro = ["Di Gennaro", "Martinez Jo.", "Sommer",
                      "Bastoni", "Birindelli", "Celik", "Djimsiti", "Dorgu", "Ehizibue", "Lazaro", "Vojvoda",
                      "Adli", "Fazzini", "Frendrup", "Lazovic", "Maldini", "Oristanio", "Pulisic", "Sohm",
                      "Bonny", "Castro S.", "Colombo", "Dallinga", "Taremi", "Thuram"]

zoo_berlino = ["Marin Re.", "Ryan", "Svilar",
               "Bisseck", "Cambiaso", "Gosens", "Martin", "Masina", "Pavard", "Pongracic", "Ruggeri",
               "Badelj", "Calhanoglu", "Chukwueze", "Kone' M.", "Le Fee", "Malinovskyi", "Man", "Thuram K.",
               "Almqvist", "Gudmundsson A.", "Lukaku", "Raspadori", "Simeone", "Thauvin"]

storditi = ["Provedel", "Scuffet", "Skorupski",
            "Dossena", "Gila", "Hernandez T.", "Kolasinac", "Miranda J.", "Romagnoli", "Tchatchoua", "Vasquez",
            "Freuler", "Koopmeiners", "Nicolussi Caviglia", "Oudin", "Pasalic", "Strefezza", "Tete Morente", "Zaccagni",
            "Adams C.", "Beltran L.", "Kean", "Kvaratskhelia", "Sanabria", "Soule'"]

ndicka = ["Gollini", "Suzuki", "Terracciano",
          "Bremer", "Circati", "Coco", "Coulibaly W.", "Gaspar K.", "Mancini", "Olivera", "Rrahmani",
          "Brescianini", "Busio", "Ederson D.s.", "Frattesi", "Gaetano", "Kastanos", "Pessina", "Suslov",
          "Cutrone", "Isaksen", "Lucca", "Mihaila", "Tengstedt", "Vlahovic"]


data_ac_st_leonards = get_data_team_alba(ac_st_leonards)
data_tuttoculo = get_data_team_alba(tuttoculo)
data_astolfone = get_data_team_alba(astolfone)
data_tartan_viola = get_data_team_alba(tartan_viola)
data_schalke104 = get_data_team_alba(schalke104)
data_real_calloni = get_data_team_alba(real_calloni)
data_olympique_nicastro = get_data_team_alba(olympique_nicastro)
data_zoo_berlino = get_data_team_alba(zoo_berlino)
data_storditi = get_data_team_alba(storditi)
data_ndicka = get_data_team_alba(ndicka)

players_taken = ac_st_leonards + tuttoculo + astolfone + tartan_viola + schalke104 + real_calloni + olympique_nicastro + zoo_berlino + storditi + ndicka
list_data_teams = [data_ac_st_leonards, data_tuttoculo, data_astolfone, data_tartan_viola, data_schalke104,
                   data_real_calloni, data_olympique_nicastro, data_zoo_berlino, data_storditi, data_ndicka]

data_players_taken = {
    'draft_2324': players_2324_df[np.isin(players_2324_df["Nome"], players_taken)],
    'draft_2425': players_2425_df[np.isin(players_2425_df["Nome"], players_taken)],
    'stats_2324': stats_2324_df[np.isin(stats_2324_df["Nome"], players_taken)],
    'stats_2425': stats_2425_df[np.isin(stats_2425_df["Nome"], players_taken)],
}
data_players_avail = {
    'draft_2324': players_2324_df[np.invert(np.isin(players_2324_df["Nome"], players_taken))],
    'draft_2425': players_2425_df[np.invert(np.isin(players_2425_df["Nome"], players_taken))],
    'stats_2324': stats_2324_df[np.invert(np.isin(stats_2324_df["Nome"], players_taken))],
    'stats_2425': stats_2425_df[np.invert(np.isin(stats_2425_df["Nome"], players_taken))],
}

# the first is not true anymore, as some players are not in Serie A anymore
# assert len(data_players_avail['draft_2425']) == len(players_2425_df["Nome"]) - 250
assert len(data_players_avail['stats_2425']) == len(stats_2425_df["Nome"]) - 250

In [13]:
data_players_taken['stats_2324'].sort_values(by='Fm', ascending=False)

,Id,R,Rm,Nome,Squadra,Pv,Mv,Fm,Gf,Gs,Rp,Rc,R+,R-,Ass,Amm,Esp,Au
524,2764,A,Pc,Martinez L.,Inter,33,6.65,8.73,24,0,0,3,2,1,2,5,0,0
525,309,A,A,Dybala,Roma,27,6.48,8.20,13,0,0,7,7,0,9,3,0,0
529,4871,A,Pc,Thuram,Inter,35,6.54,7.81,13,0,0,0,0,0,7,3,0,0
301,2194,C,M;C,Calhanoglu,Inter,32,6.47,7.70,13,0,0,10,10,0,3,5,0,0
302,5800,C,T;A,Gudmundsson A.,Genoa,35,6.47,7.64,14,0,0,5,4,1,4,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22,4,P,Por,Sportiello,Milan,7,6.14,4.57,0,11,0,0,0,0,0,0,0,0
21,4867,P,Por,Turati,Frosinone,31,6.19,4.42,0,58,1,0,0,0,0,0,0,0
19,574,P,Por,Scuffet,Cagliari,31,6.13,4.31,0,55,0,0,0,0,0,3,0,0
623,4463,A,Pc,Esposito Se.,Inter,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0
115,2160,D,E,Gosens,Inter,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0

In [45]:
Filter(column='Squadra', operation='eq', value='Atalanta').apply_to_df(data_players_avail['stats_2425'])

,Id,R,Rm,Nome,Squadra,Pv,Mv,Fm,Gf,Gs,Rp,Rc,R+,R-,Ass,Amm,Esp,Au
23,2792,P,Por,Musso,Atalanta,1,6.00,6.00,0,0,0,0,0,0,0,0,0,0
31,2297,P,Por,Rossi F.,Atalanta,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0
71,4270,P,Por,Rui Patricio,Atalanta,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0
158,2130,D,E,Hateboer,Atalanta,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0
174,697,D,E,Cuadrado,Atalanta,7,6.00,6.21,0,0,0,0,0,0,2,1,0,0
198,5067,D,E,Bakker,Atalanta,1,6.00,6.00,0,0,0,0,0,0,0,0,0,0
237,5526,D,Dc,Scalvini,Atalanta,3,5.67,5.33,0,0,0,0,0,0,0,2,0,0
265,695,D,Dc,Toloi,Atalanta,2,5.25,5.25,0,0,0,0,0,0,0,0,0,0
294,6832,D,E,Palestra,Atalanta,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0
332,22,C,M;C,De Roon,Atalanta,20,6.08,6.45,3,0,0,0,0,0,1,5,0,0
478,6024,C,M;C,Sulemana I.,Atalanta,1,6.00,6.00,0,0,0,0,0,0,0,0,0,0
502,6834,C,C,Cassa,Atalanta,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0
506,6872,C,C;T,Manzoni,Atalanta,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0
555,2137,A,Pc,Scamacca,Atalanta,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0
564,6229,A,Pc,Toure' E.,Atalanta,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0
632,6912,A,Pc,Vlahovic V.,Atalanta,1,6.00,6.00,0,0,0,0,0,0,0,0,0,0

In [46]:
interesting_players = []
interesting_players += ['De Roon']
interesting_players += ['Dominguez B.', 'Odgaard']
interesting_players += ['Zappa', 'Marin']
interesting_players += ['Diao', 'Fadera', 'Alli']
interesting_players += ['Ismajli', 'Cacace', 'Goglichidze']
interesting_players += ['Cataldi']
interesting_players += ['Ekhator']
interesting_players += ['De Vrij']
interesting_players += ['Savona', 'Kolo Muani']
interesting_players += ['Rovella', 'Gigot', 'Pedro', 'Tchaouna', 'Vecino']
interesting_players += ['Pierotti']
interesting_players += ['Gabbia', 'Fofana Y.', 'Walker', 'Jimenez A.']
interesting_players += ['Bianco']
interesting_players += []
interesting_players += ['Hernani']
interesting_players += ['El Shaarawy', 'Pisilli', 'Shomurodov', 'Rensch']
interesting_players += ['Karamoh']
interesting_players += ['Lovric', 'Davis K.']
interesting_players += ['Zampano']
interesting_players += ['Sarr A.']

Giocatori che vanno sicuramente
- D: Godfrey, Martinez Quarta
- C: Forson O.
- A: Zapata D., Banda

Giocatori potenzialmente da liberare:
- D: Lazzari, Pavlovic
- C: Richardson, Duda
- A: Okafor, Sanchez


In ordine di preferenza:
- D: Gabbia, Jimenez A., De Vrij, Savona, Gigot, Rensch, Walker, Ismajli, Zappa, Goglichidze, Zampano, Cacace
- C: El Shaarawy, Fofana Y., Pisilli, Diao, Rovella, Alli, Cataldi, De Roon, Fadera, Marin, Lovric, Hernani, Vecino, Tchaouna, Bianco
- A: Kolo Muani, Dominguez B., Odgaard, Karamoh, Shomurodov, Sarr A., Ekhator, Pierotti, Pedro, Davis K.